[tool.poetry]
name = "dir-igor"
version = "0.1.0"
description = ""
authors = ["Сергей <kpytooooo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
